In [1]:
import pandas as pd
from thefuzz import fuzz
from thefuzz import process
#import googlemaps
import geopandas as gpd
import matplotlib.pyplot as plt
import urllib.request, json 
with urllib.request.urlopen('https://www.abgeordnetenwatch.de/api/v2/candidacies-mandates?parliament_period=161&range_end=700') as url:
    can_man = json.load(url) # used to assign voting districts to member of the Bundestag

In [2]:
#!pip install thefuzz
#!pip install levenshtein
#!pip install -U googlemaps
#!pip install geopandas
#!pip install folium matplotlib mapclassify

In [3]:
#
# The first part establishes a DataFrame with the name, email adress and voting districts of all members of parliament
#

In [4]:
# Import the document "Kürschners Volkshandbuch", which provides names and E-Mail Adresses
# The document can be downloaded here: https://www.btg-bestellservice.de/pdf/10037700.pdf; it was converted to a txt file
myfile = open("Input/Kürschners_Volkshandbuch.txt", "rt")
file = myfile.read()
# Split the huge string into a list of strings at each new line
txt_into_list = file.split("\n")
# extract all E-Mail adresses that end with @bundestag.de
result = [x for x in txt_into_list if x.startswith('E-Mail:') and x.endswith('@bundestag.de')]
mail_adress = [x.removeprefix('E-Mail: ') for x in result]
# reconstruct names by splitting them up at each dot before the @ and combining them again
names = [x.removesuffix('@bundestag.de') for x in mail_adress]
df_mail = pd.DataFrame(list(zip(names, mail_adress)),
                       columns= ['name_conc', 'mail_adress'])
df_mail[['Vorname', 'Nachname']] = df_mail.name_conc.str.split('.', expand=True)
df_mail["Name"] = df_mail['Vorname'] + " " + df_mail['Nachname']
# remove the 2 E-Mail adresses that don't correspond to members of parliament
df_mail = df_mail.dropna(subset=['Name']).reset_index(drop=True)
df_mail.to_csv('Output/Liste_MdB_Mail.csv')

In [5]:
df_mail

,name_conc,mail_adress,Vorname,Nachname,Name
0,sanae.abdi,sanae.abdi@bundestag.de,sanae,abdi,sanae abdi
1,knut.abraham,knut.abraham@bundestag.de,knut,abraham,knut abraham
2,doris.achelwilm,doris.achelwilm@bundestag.de,doris,achelwilm,doris achelwilm
3,anna.aeikens,anna.aeikens@bundestag.de,anna,aeikens,anna aeikens
4,adis.ahmetovic,adis.ahmetovic@bundestag.de,adis,ahmetovic,adis ahmetovic
...,...,...,...,...,...
625,nicolas.zippelius,nicolas.zippelius@bundestag.de,nicolas,zippelius,nicolas zippelius
626,joerg.zirwes,joerg.zirwes@bundestag.de,joerg,zirwes,joerg zirwes
627,vanessa.zobel,vanessa.zobel@bundestag.de,vanessa,zobel,vanessa zobel
628,ulrich.vonzons,ulrich.vonzons@bundestag.de,ulrich,vonzons,ulrich vonzons
629,armand.zorn,armand.zorn@bundestag.de,armand,zorn,armand zorn

In [6]:
#create a dataframe with all current members of the Bundestag from the abgeordnetenwatch JSON

mdb_wkr = pd.DataFrame([
    {
        'Name': record.get('politician').get('label'),
        'Fraktion': record.get('fraction_membership')[0].get('label'),
        'Wahlkreis': 
            None if record.get('electoral_data').get('constituency') is None 
            else record.get('electoral_data').get('constituency').get('label')
    }
    for record in can_man.get('data')
])
# remove everything in parentheses (Bundestag 2025-2029)
mdb_wkr['Wahlkreis'] = mdb_wkr['Wahlkreis'].str.replace(r"\(.*\)", "", regex=True)
# Split the number of the voting district and its name
mdb_wkr[['Wahlkreis', 'Wahlkreisname']] = mdb_wkr.Wahlkreis.str.split(" - ", n=1, expand=True)
# clean up Fraktion and delete entries like [Fraktion] seit xx.yy.zzzz
mdb_wkr['Fraktion'] = mdb_wkr['Fraktion'].str.replace(r"\sseit.*", "", regex=True)

In [7]:
# Map German special characters to their ASCII equivalents for normalization
special_char_map = {ord('ä'):'ae', ord('ü'):'ue', ord('ö'):'oe', ord('ß'):'ss'}

def normalize_name(name):
    # Lowercase, transliterate umlauts, and collapse compound name particles
    # (von, van, taher) to match the format used in the email-derived names
    x = name.lower().translate(special_char_map).replace('von ', 'von').replace('van ', 'van').replace('taher ', 'taher')
    return x

# Apply normalization to the Abgeordnetenwatch names before fuzzy matching
mdb_wkr['Name_normalized'] = mdb_wkr['Name'].apply(normalize_name)

# Fuzzy match normalized names against email-derived names using token_set_ratio,
# which is robust to different word orders and extra tokens (e.g. middle names, titles)
mdb_wkr['Name_fuzzy'] = mdb_wkr['Name_normalized'].apply(
    lambda x: process.extractOne(x, df_mail['Name'], 
    scorer=fuzz.token_set_ratio)
)

# Split fuzzy match result tuple (matched name, score, index) into separate columns
mdb_wkr[['Name_matched', 'Score', 'Index']] = pd.DataFrame(
    mdb_wkr['Name_fuzzy'].tolist(), index=mdb_wkr.index
)

# Inspect the 5 worst matches to verify and determine an appropriate score cutoff
print(mdb_wkr.nsmallest(5, 'Score')[['Name', 'Name_matched', 'Score']])

                          Name        Name_matched  Score
2              David Mandrella       david gregosz     57
1                Stefan Glaser      stefan moeller     74
0              Christoph Naser   christoph birghan     75
232              Karoline Otte           karo otte     82
165  Catarina dos Santos-Wintz  catarina dossantos     84

In [8]:
# Set score cutoff based on inspection of lowest matches above.
# Matches below this threshold are considered incorrect and set to None.
# MdBs without a match are likely missing from the email list (e.g. new members).
SCORE_CUTOFF = 76
mdb_wkr.loc[mdb_wkr['Score'] < SCORE_CUTOFF, ['Name_matched', 'Score', 'Index']] = None
mdb_wkr

,Name,Fraktion,Wahlkreis,Wahlkreisname,Name_normalized,Name_fuzzy,Name_matched,Score,Index
0,Christoph Naser,CDU/CSU,290,Tübingen,christoph naser,"(christoph birghan, 75, 53)",NaN,NaN,NaN
1,Stefan Glaser,CDU/CSU,282,Lörrach – Müllheim,stefan glaser,"(stefan moeller, 74, 374)",NaN,NaN,NaN
2,David Mandrella,SPD,231,Amberg,david mandrella,"(david gregosz, 57, 182)",NaN,NaN,NaN
3,Mayra Vriesema,BÜNDNIS 90/­DIE GRÜNEN,NaN,NaN,mayra vriesema,"(mayra vriesema, 100, 582)",mayra vriesema,100.0,582.0
4,Lisa Schubert,Die Linke,106,Düsseldorf II,lisa schubert,"(lisa schubert, 100, 508)",lisa schubert,100.0,508.0
...,...,...,...,...,...,...,...,...,...
624,Adis Ahmetović,SPD,41,Stadt Hannover I,adis ahmetović,"(adis ahmetovic, 93, 4)",adis ahmetovic,93.0,4.0
625,Anna Aeikens,CDU/CSU,67,Börde – Salzlandkreis,anna aeikens,"(anna aeikens, 100, 3)",anna aeikens,100.0,3.0
626,Doris Achelwilm,Die Linke,54,Bremen I,doris achelwilm,"(doris achelwilm, 100, 2)",doris achelwilm,100.0,2.0
627,Knut Abraham,CDU/CSU,65,Elbe-Elster – Oberspreewald-Lausitz,knut abraham,"(knut abraham, 100, 1)",knut abraham,100.0,1.0
628,Sanae Abdi,SPD,92,Köln I,sanae abdi,"(sanae abdi, 100, 0)",sanae abdi,100.0,0.0

In [ ]:
# Merge mdb_wkr with df_mail on the fuzzy-matched name column, adding only the email address
mdb_final = pd.merge(mdb_wkr, df_mail[['Name', 'mail_adress']], left_on='Name_matched', right_on='Name', how='left')
# Drop intermediate columns from the fuzzy matching process
mdb_final = mdb_final.drop(columns=['Name_normalized', 'Name_fuzzy', 'Name_matched', 'Score', 'Index', 'Name_y'])
# Inspect MdBs without a matched email address — likely newly elected members not yet in the Kürschners Volkshandbuch
mdb_final[mdb_final['mail_adress'].isna()]

            Name_x Fraktion Wahlkreis        Wahlkreisname mail_adress
0  Christoph Naser  CDU/CSU       290            Tübingen          NaN
1    Stefan Glaser  CDU/CSU       282  Lörrach – Müllheim          NaN
2  David Mandrella      SPD       231              Amberg          NaN

In [ ]:
# Manually add email addresses for MdBs missing from the Kürschners Volkshandbuch
# These are new members whose emails follow the standard vorname.nachname@bundestag.de pattern
# Verified against https://www.bundestag.de/abgeordnete
manual_mails = {
    'Christoph Naser': 'christoph.naser@bundestag.de',
    'Stefan Glaser': 'stefan.glaser@bundestag.de',
    'David Mandrella': 'david.mandrella@bundestag.de'
}

for name, mail in manual_mails.items():
    mdb_final.loc[mdb_final['Name_x'] == name, 'mail_adress'] = mail
    
mdb_final

,Name_x,Fraktion,Wahlkreis,Wahlkreisname,mail_adress
0,Christoph Naser,CDU/CSU,290,Tübingen,christoph.naser@bundestag.de
1,Stefan Glaser,CDU/CSU,282,Lörrach – Müllheim,stefan.glaser@bundestag.de
2,David Mandrella,SPD,231,Amberg,david.mandrella@bundestag.de
3,Mayra Vriesema,BÜNDNIS 90/­DIE GRÜNEN,NaN,NaN,mayra.vriesema@bundestag.de
4,Lisa Schubert,Die Linke,106,Düsseldorf II,lisa.schubert@bundestag.de
...,...,...,...,...,...
624,Adis Ahmetović,SPD,41,Stadt Hannover I,adis.ahmetovic@bundestag.de
625,Anna Aeikens,CDU/CSU,67,Börde – Salzlandkreis,anna.aeikens@bundestag.de
626,Doris Achelwilm,Die Linke,54,Bremen I,doris.achelwilm@bundestag.de
627,Knut Abraham,CDU/CSU,65,Elbe-Elster – Oberspreewald-Lausitz,knut.abraham@bundestag.de
628,Sanae Abdi,SPD,92,Köln I,sanae.abdi@bundestag.de

In [38]:
mdb_final.to_csv('Output/MdBs_Wahlkreise_Mail.csv')
mdb_final

,Name_x,Fraktion,Wahlkreis,Wahlkreisname,mail_adress
0,Christoph Naser,CDU/CSU,290,Tübingen,christoph.naser@bundestag.de
1,Stefan Glaser,CDU/CSU,282,Lörrach – Müllheim,stefan.glaser@bundestag.de
2,David Mandrella,SPD,231,Amberg,david.mandrella@bundestag.de
3,Mayra Vriesema,BÜNDNIS 90/­DIE GRÜNEN,NaN,NaN,mayra.vriesema@bundestag.de
4,Lisa Schubert,Die Linke,106,Düsseldorf II,lisa.schubert@bundestag.de
...,...,...,...,...,...
624,Adis Ahmetović,SPD,41,Stadt Hannover I,adis.ahmetovic@bundestag.de
625,Anna Aeikens,CDU/CSU,67,Börde – Salzlandkreis,anna.aeikens@bundestag.de
626,Doris Achelwilm,Die Linke,54,Bremen I,doris.achelwilm@bundestag.de
627,Knut Abraham,CDU/CSU,65,Elbe-Elster – Oberspreewald-Lausitz,knut.abraham@bundestag.de
628,Sanae Abdi,SPD,92,Köln I,sanae.abdi@bundestag.de

In [ ]:
#
# The second part establishes a DataFrame with all universities and their corresponding voting districts
#

In [ ]:
# Do this only if you have a valid Google Maps API key. If you don't have one skip this cell and proceed with the next one. You'll find a hs_liste_koordinaten.csv file with all coordinates in the output folder. 

api = open("Google maps api.txt", "rt")
api_str = api.read()
# Add your individual Google Maps API key
gmaps = googlemaps.Client(key=api_str)

# import DataFrame with a list of all universities in Germany. Concatenate the adressess
df_hochschulen = pd.read_csv('hs_liste.txt', sep='\t', dtype=str)
adress = df_hochschulen['Straße'] + ', ' + df_hochschulen['Postleitzahl (Hausanschrift)'] + ', ' + df_hochschulen['Ort (Hausanschrift)']
df_hochschulen['Adresse'] = adress

# find the coordinates for all university adresses. Store the values in separate lists
lattitude = []
longitude = []
# Do this only once since it grabs the information via the googlemaps API which isn't technically free
for i in df_hochschulen.index:
    x = gmaps.geocode(df_hochschulen['Adresse'][i])
    lattitude.append(x[0].get('geometry').get('location')['lat'])
    longitude.append(x[0].get('geometry').get('location')['lng'])
# add the coordinates to the original DataFrame and save it.
df_hochschulen['Latitude'] = lattitude
df_hochschulen['Longitude'] = longitude
df_hochschulen.to_csv('Output\hs_liste_koordinaten.csv', sep='\t')

In [ ]:
# Import the shp files of all voting districts in Germany and change their reference system to degrees
# download the zip file from: https://www.bundeswahlleiterin.de/dam/jcr/fc2f7796-cc84-4f89-b475-4439fcc8fa07/btw21_geometrie_wahlkreise_shp.zip and extract to \Wahlkreise
# You can find all kind of data regarding voting districts here: https://www.bundeswahlleiterin.de/bundestagswahlen/2021/wahlkreiseinteilung/downloads.html
Wahlkreise = gpd.read_file('Wahlkreise\Geometrie_Wahlkreise_20DBT.shp')
Wahlkreise_Grad = Wahlkreise.to_crs("EPSG:4326")

In [ ]:
# make df_hochschulen DataFrame a geopanda GeoDataFrame by specifying the columns with longitude and latitude and specifying the degree reference system
df_hochschulen = pd.read_csv('Output\hs_liste_koordinaten.csv', sep='\t') # load hs_liste_koordinaten.csv in case you don't have a Google Maps API
df_hochschulen_shp = gpd.GeoDataFrame(
    df_hochschulen, geometry=gpd.points_from_xy(df_hochschulen.Longitude, df_hochschulen.Latitude), crs="EPSG:4326"
)

In [ ]:
# Optional: plot all universities onto the borders of all voting districts
ax = Wahlkreise_Grad.plot(color="white", edgecolor="black")
df_hochschulen_shp.plot(ax = ax, color = 'red', markersize = 2)

In [ ]:
# assign the voting districts to the universities
df_hochschulen_wkr = gpd.tools.sjoin(df_hochschulen_shp, Wahlkreise_Grad, predicate = 'within', how = 'left')
# export the DataFrame
df_hochschulen_wkr.to_csv('Output\hs_liste_koordinaten_Wahlkreise.csv', sep='\t')

In [ ]:
#
# The third part combines universities and member of parliament
#

In [ ]:
# Create a DataFrame that combines the names, Email-Adresses and the names of universities
list_hs_kurz = []
list_hs_lang = []
for i in data_name_party_adress_wkr.index:
    list_hs_kurz.append(df_hochschulen_wkr[(df_hochschulen_wkr.WKR_NR == data_name_party_adress_wkr['Wahlkreis'][i])]['Hochschulkurzname'].tolist())
    list_hs_lang.append(df_hochschulen_wkr[(df_hochschulen_wkr.WKR_NR == data_name_party_adress_wkr['Wahlkreis'][i])]['Hochschulname'].tolist())

data_name_party_adress_wkr_hs = data_name_party_adress_wkr
data_name_party_adress_wkr_hs['HS_Kurzname'] = list_hs_kurz
data_name_party_adress_wkr_hs['HS_Name'] = list_hs_lang

In [ ]:
# remove all MdBs that don't represent a district with at least 1 university
data_name_party_adress_wkr_hs = data_name_party_adress_wkr_hs[data_name_party_adress_wkr_hs['HS_Name'].map(lambda d: len(d)) > 0]
# drop unimportant columns
data_name_party_adress_wkr_hs.drop(['Unnamed: 0', 'Nachname', 'Vorname', 'junk', 'Wahlkreisname'], axis=1, inplace=True)
data_name_party_adress_wkr_hs.to_csv('Output\Liste_MdB_Name_Partei_Adresse_Wahlkreis_Hochschule.csv', sep='\t')

In [ ]:
# Create a DataFrame that combines, universities, Names and Email-Adresses of the MdBs

#first create empty lists for the names and adresses for the invdividual parties
SPD_Name = []
SPD_Adr = []
CDU_Name = []
CDU_Adr = []
Green_Name = []
Green_Adr = []
FDP_Name = []
FDP_Adr = []
Linke_Name = []
Linke_Adr = []
AFD_Name = []
AFD_Adr = []

# iterate through each row of df_hochschulen_wkr and look in data_name_party_adress_wkr whether there is an MdB of the respective party. If not append 'none' to the lists, if yes append the Name and Email Adresses to the respective lists
for i in df_hochschulen_wkr.index:
    if len(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'SPD')]['Name']) == 1:
        SPD_Name.append(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'SPD')]['Name'].reset_index(drop=True)[0])
        SPD_Adr.append(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'SPD')]['mail_adress'].reset_index(drop=True)[0])
    else:
        SPD_Name.append('None')
        SPD_Adr.append('None')
    
    if len(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'CDU/CSU')]['Name']) == 1:
        CDU_Name.append(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'CDU/CSU')]['Name'].reset_index(drop=True)[0])
        CDU_Adr.append(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'CDU/CSU')]['mail_adress'].reset_index(drop=True)[0])
    else:
        CDU_Name.append('None')
        CDU_Adr.append('None')

    if len(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'Bündnis 90/Die Grünen')]['Name']) == 1:
        Green_Name.append(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'Bündnis 90/Die Grünen')]['Name'].reset_index(drop=True)[0])
        Green_Adr.append(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'Bündnis 90/Die Grünen')]['mail_adress'].reset_index(drop=True)[0])
    else:
        Green_Name.append('None')
        Green_Adr.append('None')

    if len(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'FDP')]['Name']) == 1:
        FDP_Name.append(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'FDP')]['Name'].reset_index(drop=True)[0])
        FDP_Adr.append(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'FDP')]['mail_adress'].reset_index(drop=True)[0])
    else:
        FDP_Name.append('None')
        FDP_Adr.append('None')

    if len(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'Die Linke')]['Name']) == 1:
        Linke_Name.append(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'Die Linke')]['Name'].reset_index(drop=True)[0])
        Linke_Adr.append(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'Die Linke')]['mail_adress'].reset_index(drop=True)[0])
    else:
        Linke_Name.append('None')
        Linke_Adr.append('None')

    if len(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'AfD')]['Name']) == 1:
        AFD_Name.append(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'AfD')]['Name'].reset_index(drop=True)[0])
        AFD_Adr.append(data_name_party_adress_wkr[(data_name_party_adress_wkr.Wahlkreis == df_hochschulen_wkr.WKR_NR[i]) & (data_name_party_adress_wkr.Partei == 'AfD')]['mail_adress'].reset_index(drop=True)[0])
    else:
        AFD_Name.append('None')
        AFD_Adr.append('None')

#Create a temporary Dataframe with the filled lists and join it with df_hochschulen_wkr
temp = pd.DataFrame(list(zip(SPD_Name, SPD_Adr, CDU_Name, CDU_Adr, Green_Name, Green_Adr, FDP_Name, FDP_Adr, Linke_Name, Linke_Adr, AFD_Name, AFD_Adr)), 
                    columns=['SPD_Name', 'SPD_Adr', 'CDU_Name', 'CDU_Adr', 'Green_Name', 'Green_Adr', 'FDP_Name', 'FDP_Adr', 'Linke_Name', 'Linke_Adr', 'AFD_Name', 'AFD_Adr']
)

df_hochschulen_wkr_mdb = pd.concat([df_hochschulen_wkr, temp], axis = 1, join = 'inner')

In [ ]:
# Create a new DataFrame with only important columns
df_hochschulen_wkr_mdb_strip = df_hochschulen_wkr_mdb[['Hochschulkurzname', 'Hochschulname', 'WKR_NR', 'SPD_Name', 'SPD_Adr', 'CDU_Name', 'CDU_Adr', 'Green_Name', 'Green_Adr', 'FDP_Name', 'FDP_Adr', 'Linke_Name', 'Linke_Adr', 'AFD_Name', 'AFD_Adr', 'Hochschultyp', 'Trägerschaft', 'Bundesland']].copy()
df_hochschulen_wkr_mdb_strip.to_csv('Output\hs_liste_Wahlkreise_mdb.csv', sep='\t')